import { of, throwError } from 'rxjs';
import { catchError, finalize } from 'rxjs/operators';

const l = console.log;

throwError("ğŸ’©").subscribe({
  error: e => l(`Error: ${e}`)
})

throwError("ğŸ’©").pipe(
  catchError(e => of("No worries. Sorted!ğŸ˜ƒ")),
  finalize(() => { l('finalize'); }),
).subscribe(v => l(v));


// output:
//
// Error: ğŸ’©
// No worries. Sorted!ğŸ˜ƒ
// finalize
